name: Android Build

on:
  push:
    branches: [ "feature/native-android", "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo "$KEYSTORE_BASE64" | base64 -d > app/release.jks

    - name: Build with Gradle
      env:
        KEYSTORE_PATH: release.jks
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Get Release Version
      id: get_version
      run: |
        VERSION_NAME=$(grep "versionName" app/build.gradle.kts | awk -F'=' '{print $2}' | tr -d ' "')
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MagicWord-v${{ steps.get_version.outputs.VERSION_NAME }}
        path: app/build/outputs/apk/release/app-release.apk

    - name: Rename APK
      run: |
        cp app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/MagicWord-v${{ steps.get_version.outputs.VERSION_NAME }}.apk
        cp app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/MagicWord.apk

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION_NAME }}
        name: Release v${{ steps.get_version.outputs.VERSION_NAME }}
        files: |
          app/build/outputs/apk/release/MagicWord-v${{ steps.get_version.outputs.VERSION_NAME }}.apk
          app/build/outputs/apk/release/MagicWord.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push APK to Repo
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        cp app/build/outputs/apk/release/app-release.apk MagicWordLatest.apk
        git add MagicWordLatest.apk
        git commit -m "Update MagicWordLatest.apk [skip ci]" || echo "No changes to commit"
        git push origin main
